"LR": 0.0005
"NUM_ENVS": 1
"NUM_STEPS": 8
"TOTAL_TIMESTEPS": 16
"UPDATE_EPOCHS": 1
"NUM_MINIBATCHES": 1
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "coin_game"
"REW_SHAPING_HORIZON": 2.5e6 # for how many timesteps add a shaping reward
"SHAPING_BEGIN": 1e6
"ENV_KWARGS": 
  "num_agents" : 2
  "num_inner_steps" : 10
  "shared_rewards" : False # Attention: switch to False for individual rewards 
  "cnn" : True
  "jit" : True
  

"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1
"True": True

"REWARD": "individual" # individual; common
"GIF_NUM_FRAMES": 10
"PARAMETER_SHARING": True

# WandB Params
"ENTITY": "rohit-chawla28"
"PROJECT": "socialjax-ippo"
"WANDB_MODE" : "online"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD # COMMON_REWARD
