"LR": 0.0005
"NUM_ENVS": 256
"NUM_STEPS": 1000
"TOTAL_TIMESTEPS": 3e8
"UPDATE_EPOCHS": 2
"NUM_MINIBATCHES": 500
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "harvest_common_open"
"REW_SHAPING_HORIZON": 2.5e6 # for how many timesteps add a shaping reward
"SHAPING_BEGIN": 1e6
"ENV_KWARGS": 
  "num_agents" : 7
  "num_inner_steps" : 1000
  "shared_rewards" : False  # Attention: switch to False for individual rewards; True for common rewards 
  "cnn" : True
  "jit" : True
  "map_ASCII" : ["AAA    A  WW  A    AAA",
                 "AA    AAA WW AAA    AA",
                 "A    AAAAAWWAAAAA    A",
                 "      AAA WW AAA      ",
                 "       A  WW  A       ",
                 "  A       WW       A  ",
                 " AAA  Q   WW   Q  AAA ",
                 "AAAAA     WW     AAAAA",
                 " AAA  WWWWWWWWWW  AAA ",
                 "  A       WW       A  ",
                 "WWWWWWWWW WW WWWWWWWWW",
                 "          WW          ",
                 "  WWWWWWWWWWWWWWWWWW  ",
                 "  P P P P P P P P P   ",
                 " P P P P P P P P P P  ",
                ]
  

"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1
"TUNE": True

"REWARD": "individual" # individual; common
"GIF_NUM_FRAMES": 25
"PARAMETER_SHARING": True

# WandB Params
"ENTITY": "rohit-chawla28"
"PROJECT": "socialjax-ippo"
"WANDB_MODE" : "online"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD # COMMON_REWARD
